### ISSUE TITLE
no scripts are working?

### ISSUE THREAD

**Issue by Poootaatoooo** [rastapasta/pokemon-go-mitm-node#110]
none of the example scripts I tried are working (nothing happens in the terminal window after listening, and nothing is working ingame)... here's how I set up the proxy http://i.imgur.com/wnbbJuD.png . I've also tried it on ProxyDroid, but it doesn't even authenticate with that. I'm running the latest pokemon go app version, with the xposed model, and the certificate installed in system-trusted, and I'm running android version 6.0.1, I don't really know where I'm going wrong with this, can anyone help?

thanks,

**Comment by darkoulis12** [comment]
1st what windows you use?
2) you use ubuntu?
3) did you proxy bridge
virtual mahcine-your android emulator?

**Comment by Poootaatoooo** [comment]
I'm using ubuntu and a physical phone

**Comment by darkoulis12** [comment]
so you must bridge ubuntu and physical phone to "Listen"  8081port :)
at ubuntu press network(at search)
check videos at youtube

**Comment by Poootaatoooo** [comment]
i dont really understand what you're saying... could you give me a link to a youtube video that would help me? thanks

**Comment by Poootaatoooo** [comment]
by the way im not in a virtual machine,

**Comment by darkoulis12** [comment]
https://www.youtube.com/watch?v=edLl9tEg7oI

**Comment by Sapphireflames** [comment]
You have to use port 8081 when creating the server from Ubuntu.
When you connect via your phone, use the IP as the hostname and set the
port to 8081

On 4 Aug 2016 4:25 p.m., "Poootaatoooo" <notifications@github.com> wrote:

i dont really understand what you're saying... could you give me a link to
a youtube video that would help me? thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rastapasta/pokemon-go-mitm-node/issues/110#issuecomment-237588181>,
or mute the thread

**Comment by darkoulis12** [comment]
btw cuase the will not understand,what ip use as a hostname???your ip?

**Comment by Poootaatoooo** [comment]
so for the hostname do i use my public ip or the local ip that I'm running the server on?

**Comment by darkoulis12** [comment]
whatismyip


enter in dat damn site :D and use the same 
have fun

**Comment by Poootaatoooo** [comment]
"unable to authenticate" in pokemon go

**Comment by darkoulis12** [comment]
at your phone put your public,if not work use your local ;)

**Comment by Poootaatoooo** [comment]
thank you so much, I tried both local and public yesterday but it didn't work, but now it's working! thank you both!

**Comment by Sapphireflames** [comment]
Use your local IP, not your public one

**Comment by Poootaatoooo** [comment]
yeah i know, I tried both and local worked, thanks though!
