### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by john5788** [rastapasta/pokemon-go-mitm-node#71]
Is it just me or do some of the images not load? Running example.replacePokemons.coffee and while the small preview images of Mew and Mewtwo load, clicking on the Pokemon itself does not show the larger animated character.

**Comment by trisk** [comment]
I haven't tried spoofing Pokémon IDs yet, but the 3D models on the Pokémon detail screens are downloaded on the fly. It would not be surprising if some of them are not yet available.

**Comment by blackms** [comment]
That example doesn't works for me.

**Comment by blackms** [comment]
It works...

**Comment by peacey** [comment]
@john5788, did you install the security certificate that was generated to your phone? I had the same problem as you until I installed the certificate on my phone, then the images started showing up. I suspect the images are loaded through a secure connection, because I was seeing HTTPS_CLIENT_ERROR messages (in debug mode) when I tried to load images before I installed the certificate. I suppose you can't communicate with a secure server though an un-secure connection. Note I am using the Pokemon Go Xposed module too.

@trisk Nope, that's good thinking though. I thought that too before I fixed the issue. The 3D models seem to already be complete because they are loading fine when the certificate is installed too.

**Comment by john5788** [comment]
I did download the certificates and install them. The issue is not consistent, perhaps maybe something on server side. Sometimes the images will load, othertimes will not. I'll close this issue since it doesn't seem to be related to this project directly.
